[programs.devnet]
myepicproject = "7e8jEVGt6gPAYLYCbfGzfCSrEvy6UdmN7cUXNcYGaQM8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/pwarrior/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
